name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: MtoseD
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Zurich
          
          # 🈷️ Languages Plugin
          plugin_languages: yes
          #plugin_languages_ignored: html, css # (Optional) Hide languages you don't want to show
          plugin_languages_limit: 8           # Show a maximum of 8 languages
          plugin_languages_colors: github     # Use official GitHub colors for languages
          plugin_languages_details: bytes-size, percentage
          
          # 📅 Isometric Commit Calendar Plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year # Options: 'half-year' or 'full-year'
